# -*- coding: utf-8 -*-
"""
/***************************************************************************
 featuresWithGPS
                                 A QGIS plugin
 Features with GPS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-03-03
        copyright            : (C) 2020 by TH for MHTC
        email                : th@mhtc.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load featuresWithGPS class from file featuresWithGPS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .featuresWithGPS import featuresWithGPS
    return featuresWithGPS(iface)
