# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MovingTrafficSigns_200619.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(739, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMaximumSize(QtCore.QSize(750, 550))
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.button_box = QtWidgets.QDialogButtonBox(Dialog)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.gridLayout.addWidget(self.button_box, 2, 2, 1, 1)
        self.GeometryID = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GeometryID.sizePolicy().hasHeightForWidth())
        self.GeometryID.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.GeometryID.setFont(font)
        self.GeometryID.setInputMask("")
        self.GeometryID.setReadOnly(True)
        self.GeometryID.setPlaceholderText("")
        self.GeometryID.setObjectName("GeometryID")
        self.gridLayout.addWidget(self.GeometryID, 0, 1, 1, 1)
        self.Details = QtWidgets.QTabWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Details.sizePolicy().hasHeightForWidth())
        self.Details.setSizePolicy(sizePolicy)
        self.Details.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Details.setFont(font)
        self.Details.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Details.setMouseTracking(True)
        self.Details.setAcceptDrops(True)
        self.Details.setObjectName("Details")
        self.RestrictionDetails = QtWidgets.QWidget()
        self.RestrictionDetails.setFocusPolicy(QtCore.Qt.NoFocus)
        self.RestrictionDetails.setObjectName("RestrictionDetails")
        self.formLayout = QtWidgets.QFormLayout(self.RestrictionDetails)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.Type1_4 = QtWidgets.QLabel(self.RestrictionDetails)
        self.Type1_4.setObjectName("Type1_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Type1_4)
        self.SignType_1 = QtWidgets.QComboBox(self.RestrictionDetails)
        self.SignType_1.setMaxVisibleItems(5)
        self.SignType_1.setMinimumContentsLength(5)
        self.SignType_1.setObjectName("SignType_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.SignType_1)
        self.Type1_5 = QtWidgets.QLabel(self.RestrictionDetails)
        self.Type1_5.setObjectName("Type1_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Type1_5)
        self.SignType_2 = QtWidgets.QComboBox(self.RestrictionDetails)
        self.SignType_2.setObjectName("SignType_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.SignType_2)
        self.Type1_6 = QtWidgets.QLabel(self.RestrictionDetails)
        self.Type1_6.setObjectName("Type1_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Type1_6)
        self.SignType_3 = QtWidgets.QComboBox(self.RestrictionDetails)
        self.SignType_3.setObjectName("SignType_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.SignType_3)
        self.lbl_Condition = QtWidgets.QLabel(self.RestrictionDetails)
        self.lbl_Condition.setMinimumSize(QtCore.QSize(90, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_Condition.setFont(font)
        self.lbl_Condition.setObjectName("lbl_Condition")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_Condition)
        self.SignConditionTypeID = QtWidgets.QComboBox(self.RestrictionDetails)
        self.SignConditionTypeID.setObjectName("SignConditionTypeID")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.SignConditionTypeID)
        self.lbl_Illumination = QtWidgets.QLabel(self.RestrictionDetails)
        self.lbl_Illumination.setMinimumSize(QtCore.QSize(90, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_Illumination.setFont(font)
        self.lbl_Illumination.setObjectName("lbl_Illumination")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lbl_Illumination)
        self.SignIlluminationTypeID = QtWidgets.QComboBox(self.RestrictionDetails)
        self.SignIlluminationTypeID.setObjectName("SignIlluminationTypeID")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.SignIlluminationTypeID)
        self.label_3 = QtWidgets.QLabel(self.RestrictionDetails)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lbl_Notes = QtWidgets.QLabel(self.RestrictionDetails)
        self.lbl_Notes.setObjectName("lbl_Notes")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.lbl_Notes)
        self.AssetReference = QtWidgets.QLineEdit(self.RestrictionDetails)
        self.AssetReference.setObjectName("AssetReference")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.AssetReference)
        self.label_7 = QtWidgets.QLabel(self.RestrictionDetails)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.SignOrientationTypeID = QtWidgets.QComboBox(self.RestrictionDetails)
        self.SignOrientationTypeID.setObjectName("SignOrientationTypeID")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.SignOrientationTypeID)
        self.label_11 = QtWidgets.QLabel(self.RestrictionDetails)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.SignType_4 = QtWidgets.QComboBox(self.RestrictionDetails)
        self.SignType_4.setObjectName("SignType_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.SignType_4)
        self.SignsAttachmentTypeID = QtWidgets.QComboBox(self.RestrictionDetails)
        self.SignsAttachmentTypeID.setObjectName("SignsAttachmentTypeID")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.SignsAttachmentTypeID)
        self.label_12 = QtWidgets.QLabel(self.RestrictionDetails)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.Notes = QtWidgets.QTextEdit(self.RestrictionDetails)
        self.Notes.setObjectName("Notes")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.Notes)
        self.Details.addTab(self.RestrictionDetails, "")
        self.Geometry = QtWidgets.QWidget()
        self.Geometry.setObjectName("Geometry")
        self.formLayout_2 = QtWidgets.QFormLayout(self.Geometry)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lbl_RoadName = QtWidgets.QLabel(self.Geometry)
        self.lbl_RoadName.setMinimumSize(QtCore.QSize(90, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_RoadName.setFont(font)
        self.lbl_RoadName.setObjectName("lbl_RoadName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_RoadName)
        self.RoadName = QtWidgets.QLineEdit(self.Geometry)
        self.RoadName.setObjectName("RoadName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.RoadName)
        self.lbl_USRN = QtWidgets.QLabel(self.Geometry)
        self.lbl_USRN.setMinimumSize(QtCore.QSize(90, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_USRN.setFont(font)
        self.lbl_USRN.setObjectName("lbl_USRN")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_USRN)
        self.USRN = QtWidgets.QLineEdit(self.Geometry)
        self.USRN.setObjectName("USRN")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.USRN)
        self.label_8 = QtWidgets.QLabel(self.Geometry)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.LastUpdateDateTime = QtWidgets.QDateTimeEdit(self.Geometry)
        self.LastUpdateDateTime.setReadOnly(True)
        self.LastUpdateDateTime.setObjectName("LastUpdateDateTime")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.LastUpdateDateTime)
        self.label_2 = QtWidgets.QLabel(self.Geometry)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_9 = QtWidgets.QLabel(self.Geometry)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.LastUpdatePerson = QtWidgets.QLineEdit(self.Geometry)
        self.LastUpdatePerson.setObjectName("LastUpdatePerson")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.LastUpdatePerson)
        self.RestrictionID = QtWidgets.QLineEdit(self.Geometry)
        self.RestrictionID.setObjectName("RestrictionID")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.RestrictionID)
        self.label_10 = QtWidgets.QLabel(self.Geometry)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.AzimuthToRoadCentreLine = QtWidgets.QLineEdit(self.Geometry)
        self.AzimuthToRoadCentreLine.setObjectName("AzimuthToRoadCentreLine")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.AzimuthToRoadCentreLine)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.Details.addTab(self.Geometry, "")
        self.PhotoTab_01 = QtWidgets.QWidget()
        self.PhotoTab_01.setObjectName("PhotoTab_01")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.PhotoTab_01)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.startCamera1 = QtWidgets.QPushButton(self.PhotoTab_01)
        self.startCamera1.setMaximumSize(QtCore.QSize(150, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../PC18-26 Carnegie Library Lambeth/Mapping/Templates/camara_foto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startCamera1.setIcon(icon)
        self.startCamera1.setCheckable(True)
        self.startCamera1.setAutoDefault(False)
        self.startCamera1.setDefault(False)
        self.startCamera1.setObjectName("startCamera1")
        self.gridLayout_2.addWidget(self.startCamera1, 2, 0, 1, 1)
        self.getPhoto1 = QtWidgets.QPushButton(self.PhotoTab_01)
        self.getPhoto1.setMaximumSize(QtCore.QSize(150, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../PC18-26 Carnegie Library Lambeth/Mapping/Templates/take-photo-icon-21.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.getPhoto1.setIcon(icon1)
        self.getPhoto1.setCheckable(False)
        self.getPhoto1.setAutoDefault(False)
        self.getPhoto1.setObjectName("getPhoto1")
        self.gridLayout_2.addWidget(self.getPhoto1, 2, 2, 1, 1)
        self.pb_zoomIn_01 = QtWidgets.QPushButton(self.PhotoTab_01)
        self.pb_zoomIn_01.setObjectName("pb_zoomIn_01")
        self.gridLayout_2.addWidget(self.pb_zoomIn_01, 0, 2, 1, 1)
        self.Photo_Widget_01 = imageLabel(self.PhotoTab_01)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Photo_Widget_01.sizePolicy().hasHeightForWidth())
        self.Photo_Widget_01.setSizePolicy(sizePolicy)
        self.Photo_Widget_01.setMaximumSize(QtCore.QSize(640, 480))
        self.Photo_Widget_01.setAutoFillBackground(True)
        self.Photo_Widget_01.setObjectName("Photo_Widget_01")
        self.gridLayout_2.addWidget(self.Photo_Widget_01, 0, 0, 1, 1)
        self.pb_zoomOut_01 = QtWidgets.QPushButton(self.PhotoTab_01)
        self.pb_zoomOut_01.setObjectName("pb_zoomOut_01")
        self.gridLayout_2.addWidget(self.pb_zoomOut_01, 1, 2, 1, 1)
        self.Details.addTab(self.PhotoTab_01, "")
        self.PhotoTab_02 = QtWidgets.QWidget()
        self.PhotoTab_02.setObjectName("PhotoTab_02")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.PhotoTab_02)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Photo_Widget_02 = QtWidgets.QLabel(self.PhotoTab_02)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Photo_Widget_02.sizePolicy().hasHeightForWidth())
        self.Photo_Widget_02.setSizePolicy(sizePolicy)
        self.Photo_Widget_02.setMaximumSize(QtCore.QSize(640, 480))
        self.Photo_Widget_02.setAutoFillBackground(True)
        self.Photo_Widget_02.setObjectName("Photo_Widget_02")
        self.gridLayout_4.addWidget(self.Photo_Widget_02, 0, 0, 1, 1)
        self.startCamera2 = QtWidgets.QPushButton(self.PhotoTab_02)
        self.startCamera2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.startCamera2.setIcon(icon)
        self.startCamera2.setCheckable(True)
        self.startCamera2.setAutoDefault(False)
        self.startCamera2.setDefault(False)
        self.startCamera2.setObjectName("startCamera2")
        self.gridLayout_4.addWidget(self.startCamera2, 1, 0, 1, 1)
        self.getPhoto2 = QtWidgets.QPushButton(self.PhotoTab_02)
        self.getPhoto2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.getPhoto2.setIcon(icon1)
        self.getPhoto2.setCheckable(False)
        self.getPhoto2.setAutoDefault(False)
        self.getPhoto2.setObjectName("getPhoto2")
        self.gridLayout_4.addWidget(self.getPhoto2, 1, 1, 1, 1)
        self.Details.addTab(self.PhotoTab_02, "")
        self.PhotoTab_03 = QtWidgets.QWidget()
        self.PhotoTab_03.setObjectName("PhotoTab_03")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.PhotoTab_03)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Photo_Widget_03 = QtWidgets.QLabel(self.PhotoTab_03)
        self.Photo_Widget_03.setAutoFillBackground(True)
        self.Photo_Widget_03.setObjectName("Photo_Widget_03")
        self.gridLayout_3.addWidget(self.Photo_Widget_03, 0, 0, 1, 1)
        self.getPhoto3 = QtWidgets.QPushButton(self.PhotoTab_03)
        self.getPhoto3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.getPhoto3.setIcon(icon1)
        self.getPhoto3.setCheckable(False)
        self.getPhoto3.setAutoDefault(False)
        self.getPhoto3.setObjectName("getPhoto3")
        self.gridLayout_3.addWidget(self.getPhoto3, 1, 2, 1, 1)
        self.startCamera3 = QtWidgets.QPushButton(self.PhotoTab_03)
        self.startCamera3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.startCamera3.setIcon(icon)
        self.startCamera3.setCheckable(True)
        self.startCamera3.setAutoDefault(False)
        self.startCamera3.setDefault(False)
        self.startCamera3.setObjectName("startCamera3")
        self.gridLayout_3.addWidget(self.startCamera3, 1, 0, 1, 1)
        self.Details.addTab(self.PhotoTab_03, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayout_4 = QtWidgets.QFormLayout(self.tab)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.ComplianceNotes = QtWidgets.QTextEdit(self.tab)
        self.ComplianceNotes.setObjectName("ComplianceNotes")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ComplianceNotes)
        self.ComplianceRestrictionSignIssue = QtWidgets.QComboBox(self.tab)
        self.ComplianceRestrictionSignIssue.setObjectName("ComplianceRestrictionSignIssue")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ComplianceRestrictionSignIssue)
        self.Details.addTab(self.tab, "")
        self.checkingTab = QtWidgets.QWidget()
        self.checkingTab.setObjectName("checkingTab")
        self.formLayout_3 = QtWidgets.QFormLayout(self.checkingTab)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_4 = QtWidgets.QLabel(self.checkingTab)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.MHTC_CheckNotes = QtWidgets.QTextEdit(self.checkingTab)
        self.MHTC_CheckNotes.setObjectName("MHTC_CheckNotes")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.MHTC_CheckNotes)
        self.label_5 = QtWidgets.QLabel(self.checkingTab)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.MHTC_CheckIssueTypeID = QtWidgets.QComboBox(self.checkingTab)
        self.MHTC_CheckIssueTypeID.setObjectName("MHTC_CheckIssueTypeID")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.MHTC_CheckIssueTypeID)
        self.FieldCheckCompleted = QtWidgets.QCheckBox(self.checkingTab)
        self.FieldCheckCompleted.setObjectName("FieldCheckCompleted")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.FieldCheckCompleted)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        self.label_14 = QtWidgets.QLabel(self.checkingTab)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.Last_MHTC_Check_UpdatePerson = QtWidgets.QLineEdit(self.checkingTab)
        self.Last_MHTC_Check_UpdatePerson.setObjectName("Last_MHTC_Check_UpdatePerson")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.Last_MHTC_Check_UpdatePerson)
        self.Last_MHTC_Check_UpdateDateTime = QtWidgets.QDateTimeEdit(self.checkingTab)
        self.Last_MHTC_Check_UpdateDateTime.setObjectName("Last_MHTC_Check_UpdateDateTime")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.Last_MHTC_Check_UpdateDateTime)
        self.label_15 = QtWidgets.QLabel(self.checkingTab)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_15)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_3.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.Details.addTab(self.checkingTab, "")
        self.gridLayout.addWidget(self.Details, 1, 0, 1, 3)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.Details.setCurrentIndex(0)
        self.button_box.accepted.connect(Dialog.accept)
        self.button_box.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Type1_4.setText(_translate("Dialog", "Sign Type 1"))
        self.Type1_5.setText(_translate("Dialog", "Sign Type 2"))
        self.Type1_6.setText(_translate("Dialog", "Sign Type 3"))
        self.lbl_Condition.setText(_translate("Dialog", "Condition:"))
        self.lbl_Illumination.setText(_translate("Dialog", "Illumination:"))
        self.label_3.setText(_translate("Dialog", "Reference:"))
        self.lbl_Notes.setText(_translate("Dialog", "Notes:"))
        self.label_7.setText(_translate("Dialog", "Orientation:"))
        self.label_11.setText(_translate("Dialog", "Sign Type 4"))
        self.label_12.setText(_translate("Dialog", "Attached to:"))
        self.Details.setTabText(self.Details.indexOf(self.RestrictionDetails), _translate("Dialog", "Restriction"))
        self.lbl_RoadName.setText(_translate("Dialog", "Road Name:"))
        self.lbl_USRN.setText(_translate("Dialog", "USRN:"))
        self.label_8.setText(_translate("Dialog", "Last Update Date:"))
        self.label_2.setText(_translate("Dialog", "Last Changed By:"))
        self.label_9.setText(_translate("Dialog", "RestrictionID:"))
        self.label_10.setText(_translate("Dialog", "Direction to Road Centreline:"))
        self.Details.setTabText(self.Details.indexOf(self.Geometry), _translate("Dialog", "Geometry"))
        self.startCamera1.setText(_translate("Dialog", "open Camera"))
        self.getPhoto1.setText(_translate("Dialog", "take Photo"))
        self.pb_zoomIn_01.setText(_translate("Dialog", "+"))
        self.Photo_Widget_01.setText(_translate("Dialog", "No photo"))
        self.pb_zoomOut_01.setText(_translate("Dialog", "-"))
        self.Details.setTabText(self.Details.indexOf(self.PhotoTab_01), _translate("Dialog", "Photo1"))
        self.Photo_Widget_02.setText(_translate("Dialog", "No photo"))
        self.startCamera2.setText(_translate("Dialog", "open Camera"))
        self.getPhoto2.setText(_translate("Dialog", "take Photo"))
        self.Details.setTabText(self.Details.indexOf(self.PhotoTab_02), _translate("Dialog", "Photo2"))
        self.Photo_Widget_03.setText(_translate("Dialog", "No photo"))
        self.getPhoto3.setText(_translate("Dialog", "take Photo"))
        self.startCamera3.setText(_translate("Dialog", "open Camera"))
        self.Details.setTabText(self.Details.indexOf(self.PhotoTab_03), _translate("Dialog", "Photo3"))
        self.label_6.setText(_translate("Dialog", "Sign -> Restriction:"))
        self.label_13.setText(_translate("Dialog", "Compliance notes:"))
        self.Details.setTabText(self.Details.indexOf(self.tab), _translate("Dialog", "Compliance"))
        self.label_4.setText(_translate("Dialog", "Check Notes:"))
        self.label_5.setText(_translate("Dialog", "Check issue type:"))
        self.FieldCheckCompleted.setText(_translate("Dialog", "Field check completed"))
        self.label_14.setText(_translate("Dialog", "Checked by:"))
        self.label_15.setText(_translate("Dialog", "Check date:"))
        self.Details.setTabText(self.Details.indexOf(self.checkingTab), _translate("Dialog", "Checking"))
        self.label.setText(_translate("Dialog", "GeometryID"))

from imagelabel import imageLabel

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

